### ISSUE TITLE
crypto.createDecipher is deprecated

### ISSUE THREAD

**Issue by Erkalos** [Richienb/crypto-json#12]
Hi,
Everything is in the title :)
This function should be use now : https://nodejs.org/api/crypto.html#crypto_crypto_createdecipheriv_algorithm_key_iv_options

Unfortunately I'm not capable to propose any update:(
(I'm a begginer)
Hope you will find someone to take this project 👍

**Comment by Erkalos** [comment]
I looked perhaps just change this line :     const decipher = crypto.createDecipher(algo, pw)
by     const decipher = crypto.createDecipheriv(algo, pw)

**Comment by roryrjb** [comment]
No one has stepped forward to maintain this project. Closing all issues. I will delete this from GitHub on the 1st May 2020. If you are still interested please step forward and I will transfer the repo or fork or download the code. Thank you for all that found any use with this code!

**Comment by perugini** [comment]
Hi @Erkalos, we've just fixed it.
